# Generated by Django 3.1.6 on 2022-03-06 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('founders', models.CharField(max_length=200)),
                ('dateFounded', models.DateField(null=True)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('num_Employees', models.IntegerField()),
                ('slug', models.SlugField()),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('industry', models.CharField(choices=[('RE', 'Real Estate'), ('TR', 'Trading'), ('SR', 'Services'), ('TT', 'Travel and Tourism'), ('HS', 'Hospitality'), ('OT', 'Others')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
