# Generated by Django 3.1.6 on 2022-03-13 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='dateFounded',
        ),
        migrations.RemoveField(
            model_name='business',
            name='description',
        ),
        migrations.RemoveField(
            model_name='business',
            name='email',
        ),
        migrations.RemoveField(
            model_name='business',
            name='founders',
        ),
        migrations.RemoveField(
            model_name='business',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='business',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='business',
            name='name',
        ),
        migrations.RemoveField(
            model_name='business',
            name='num_Employees',
        ),
        migrations.RemoveField(
            model_name='business',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='business',
            name='user',
        ),
    ]
