# Generated by Django 3.1.6 on 2022-03-07 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='dateFounded',
            new_name='date_founded',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='num_Employees',
            new_name='num_employees',
        ),
        migrations.RemoveField(
            model_name='business',
            name='slug',
        ),
    ]
