# Generated by Django 4.0.3 on 2022-03-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        
        
        
        migrations.AddField(
            model_name='business',
            name='num_employees',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='founders',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='business',
            name='industry',
            field=models.CharField(choices=[('RE', 'Real Estate'), ('TR', 'Trading'), ('SR', 'Services'), ('TT', 'Travel and Tourism'), ('HS', 'Hospitality'), ('OT', 'Others')], default='OT', max_length=2),
        ),
    ]
