# Generated by Django 4.0.3 on 2022-03-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_rename_datefounded_business_date_founded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='dateFounded',
        ),
        migrations.AddField(
            model_name='business',
            name='date_founded',
            field=models.DateField(null=True),
        ),
    ]
