# Generated by Django 3.1.6 on 2022-03-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_auto_20220307_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='founders',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='business',
            name='num_employees',
            field=models.IntegerField(default=1),
        ),
    ]
