# Generated by Django 3.1.6 on 2022-03-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_auto_20220310_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='industry',
            field=models.CharField(choices=[('RE', 'Real Estate'), ('TR', 'Trading'), ('SR', 'Services'), ('TT', 'Travel and Tourism'), ('HS', 'Hospitality'), ('OT', 'Others')], default='OT', max_length=2),
        ),
    ]
