# Generated by Django 4.0.3 on 2022-03-18 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_remove_business_datefounded_business_date_founded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='num_Employees',
        ),
    ]
