# Generated by Django 4.0.3 on 2022-03-18 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_remove_business_num_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='slug',
        ),
    ]
