# Generated by Django 4.0.2 on 2022-03-05 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('budget_category', models.CharField(choices=[('B', 'Budget'), ('M', 'Medium'), ('H', 'High-end')], max_length=1, null=True)),
                ('website', models.URLField()),
                ('reviews', models.URLField()),
                ('avg_review', models.IntegerField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboard.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('founders', models.CharField(max_length=200)),
                ('dateFounded', models.DateField()),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('num_Employees', models.IntegerField()),
                ('industry', models.CharField(choices=[('RE', 'Real Estate'), ('TR', 'Trading'), ('SR', 'Services'), ('TT', 'Travel and Tourism'), ('HS', 'Hospitality'), ('OT', 'Others')], max_length=2, null=True)),
                ('size', models.IntegerField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboard.sector')),
            ],
        ),
    ]
