# Generated by Django 4.0.2 on 2022-03-05 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_add_slug_to_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendors',
            name='last_update',
        ),
    ]
