# Generated by Django 4.0.2 on 2022-03-08 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_vendors_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sector'),
        ),
        migrations.DeleteModel(
            name='Business',
        ),
    ]
