# Generated by Django 4.0.2 on 2022-03-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_vendors_logo_alter_vendors_name_alter_vendors_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
