# Generated by Django 4.0.3 on 2022-04-06 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DM', 'Digital Marketing'), ('MA', 'Market Analysis'), ('TM', 'Team Management'), ('FA', 'Financial Analysis'), ('HR', 'Human Resoucres'), ('CS', 'Cyber Security'), ('BI', 'Business Intelligence'), ('CLD', 'Cloud Services')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('pricing', models.TextField(blank=True, max_length=12)),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('main_link', models.TextField()),
                ('account_link', models.TextField()),
                ('features', models.TextField(blank=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketplace.category')),
            ],
        ),
    ]
