# Generated by Django 4.0.3 on 2022-04-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='pricing',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
