# Generated by Django 4.0.3 on 2022-04-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_vendor_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('DM', 'Digital Marketing'), ('MA', 'Market Analysis'), ('TM', 'Team Management'), ('FA', 'Financial Analysis'), ('HR', 'Human Resoucres'), ('CS', 'Cyber Security'), ('BI', 'Business Intelligence'), ('CLD', 'Cloud Services')], max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
