# Generated by Django 4.0.3 on 2022-04-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_alter_vendor_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(null=True, upload_to='marketplace/media'),
        ),
    ]
