# Generated by Django 4.0.3 on 2022-04-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_alter_vendor_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
