# Generated by Django 4.0.3 on 2022-04-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_vendor_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
        ),
    ]
