# Generated by Django 4.0.3 on 2022-04-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_vendor_alt_1_vendor_alt_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='pricing_model',
            field=models.CharField(default='monthly', max_length=150),
        ),
    ]
