# Generated by Django 4.0.3 on 2022-04-12 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0019_category_background_category_description'),
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='startups.business')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_dashboard.dashboard')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.vendor')),
            ],
        ),
    ]
